name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:20.11.0-bookworm
      options: --user root:root
      ports:
        - 3000:3000
        - 5000:5000

    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g npm
          npm ci --no-fund --no-audit

      - name: Compile
        run: |
          npm install typescript
          ./node_modules/.bin/tsc

      - name: Run ESLint
        run: |
          npm install eslint
          npx eslint --version
          npm run eslint

      - name: Security Audit
        run: npm audit --omit=dev

      - name: Generate Documentation
        run: |
          npm install asciidoctor asciidoctor-revealjs typedoc
          npx asciidoctor --version
          npx asciidoctor-revealjs --version
          npx typedoc --version
          npm run asciidoctor
          npm run revealjs
          npm run typedoc

      - name: Publish Documentation
        run: |
          echo 'TODO: Publish documentation artifacts'

      - name: Build Docker Image
        run: |
          echo 'Building Docker Image'
          docker build -t juergenzimmermann/buch:2024.04.0 .
          echo 'Pushing Docker Image'
          docker push juergenzimmermann/buch:2024.04.0

      - name: Deployment for Kubernetes
        run: |
          echo 'Deploying to Kubernetes with Terraform/Ansible'